<?php include('Include/Headder.php') ?>
<title>Unidad 4</title>

<div class="d-flex align-items-start ">
    <div class="nav flex-column nav-pills me-3 bg-dark" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <button class="nav-link active" id="noticia_1-tab" data-bs-toggle="pill" data-bs-target="#noticia_1" type="button" role="tab" aria-controls="noticia_1" aria-selected="true">
            Actividad 1
        </button>

        <button class="nav-link" id="noticia_2-tab" data-bs-toggle="pill" data-bs-target="#noticia_2" type="button" role="tab" aria-controls="noticia_2" aria-selected="false">
            Actividad 2
        </button>

        <button class="nav-link" id="noticia_3-tab" data-bs-toggle="pill" data-bs-target="#noticia_3" type="button" role="tab" aria-controls="noticia_3" aria-selected="false">
            Actividad 3
        </button>

        <button class="nav-link" id="noticia_4-tab" data-bs-toggle="pill" data-bs-target="#noticia_4" type="button" role="tab" aria-controls="noticia_4" aria-selected="false">
            Actividad 4
        </button>



    </div>

    <div class="tab-content" id="v-pills-tabContent">
        <div class="tab-pane fade show active" id="noticia_1" role="tabpanel" aria-labelledby="noticia_1-tab">
            <br></br>
            <div class="align-text-justify">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos fuga assumenda labore ratione at rerum quibusdam ipsam eveniet cumque doloribus sequi consequuntur dolore animi itaque, atque quaerat quisquam facere autem nobis tenetur vitae quas saepe! Dolorum aspernatur fuga quam explicabo officiis aliquam consequatur deserunt dolores cupiditate eligendi cum nobis doloremque nisi voluptatem illo, maiores itaque eveniet fugiat, veniam exercitationem quo. Sit amet quam beatae quasi harum perspiciatis dolore illum ut consectetur, dolorem quo, explicabo aspernatur odio, velit debitis asperiores voluptas. Laudantium cupiditate eos laboriosam error. Ratione aliquam veniam cum error unde illo repellendus dignissimos corrupti neque eius deleniti omnis inventore praesentium laudantium id, doloremque iusto repudiandae officiis! Similique expedita cumque vel consectetur deserunt magni, perspiciatis aliquid aut beatae distinctio quo at minus corporis doloremque reprehenderit nostrum voluptatum facere voluptate quae fuga. Ipsum commodi enim accusantium dolor, obcaecati dicta? Debitis magnam architecto fugit impedit necessitatibus fugiat at iure quae assumenda quod voluptas similique labore quaerat cum illo repellat, vel dolorem nulla maiores sed consequuntur? Eum praesentium exercitationem ea nisi veritatis aut quasi, architecto quia non neque? Accusamus dolorum, nesciunt perferendis vitae ipsa nam labore reiciendis consectetur nemo voluptatum inventore, doloribus adipisci. Consequuntur quibusdam officia corrupti dolorum fugit molestiae. Quibusdam fugiat ad voluptatem, culpa facilis sed error, ratione illo enim saepe cum voluptatum explicabo eveniet, eligendi asperiores exercitationem voluptate necessitatibus dolorum recusandae facere tempora a. Error iure, eaque cupiditate facilis rem atque tenetur modi dolorum aperiam! Dicta nihil qui nam, veritatis officiis consequatur fuga dolores ullam necessitatibus molestiae autem quaerat maxime voluptatum temporibus accusantium expedita nemo facilis rem tenetur recusandae corporis eos ducimus. Ratione id molestias blanditiis ex inventore neque minus iusto, consequuntur omnis error aliquam ab accusantium dignissimos fugit eveniet. Earum, et officiis vero dicta nihil aliquid aperiam. Minima error amet esse possimus necessitatibus vero sequi labore. Nihil deleum perferendis, a excepturi tenetur nobis impedit saepe aspernatur porro. Architecto repudiandae placeat sit laborum voluptatibus veritatis quidem. Suscipit praesentium consequuntur hic reprehenderit soluta delectus libero, excepturi quis ea maxime? Cupiditate animi amet, reiciendis delectus voluptates eaque laudantium accusantium sed recusandae, id corrupti. Quod nulla est veritatis unde laudantium incidunt adipisci cupiditate optio velit repellat illum odit excepturi dolor consequuntur ad, delectus mollitia doloremque, reprehenderit reiciendis recusandae repellendus. Eaque, explicabo labore!
            </div>
        </div>

        <div class="tab-pane fade" id="noticia_2" role="tabpanel" aria-labelledby="noticia_2-tab">
            <br></br>
            <div class="align-text-justify">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos fuga assumenda labore ratione at rerum quibusdam ipsam eveniet cumque doloribus sequi consequuntur dolore animi itaque, atque quaerat quisquam facere autem nobis tenetur vitae quas saepe! Dolorum aspernatur fuga quam explicabo officiis aliquam consequatur deserunt dolores cupiditate eligendi cum nobis doloremque nisi voluptatem illo, maiores itaque eveniet fugiat, veniam exercitationem quo. Sit amet quam beatae quasi harum perspiciatis dolore illum ut consectetur, dolorem quo, explicabo aspernatur odio, velit debitis asperiores voluptas. Laudantium cupiditate eos laboriosam error. Ratione aliquam veniam cum error unde illo repellendus dignissimos corrupti neque eius deleniti omnis inventore praesentium laudantium id, doloremque iusto repudiandae officiis! Similique expedita cumque vel consectetur deserunt magni, perspiciatis aliquid aut beatae distinctio quo at minus corporis doloremque reprehenderit nostrum voluptatum facere voluptate quae fuga. Ipsum commodi enim accusantium dolor, obcaecati dicta? Debitis magnam architecto fugit impedit necessitatibus fugiat at iure quae assumenda quod voluptas similique labore quaerat cum illo repellat, vel dolorem nulla maiores sed consequuntur? Eum praesentium exercitationem ea nisi veritatis aut quasi, architecto quia non neque? Accusamus dolorum, nesciunt perferendis vitae ipsa nam labore reiciendis consectetur nemo voluptatum inventore, doloribus adipisci. Consequuntur quibusdam officia corrupti dolorum fugit molestiae. Quibusdam fugiat ad voluptatem, culpa facilis sed error, ratione illo enim saepe cum voluptatum explicabo eveniet, eligendi asperiores exercitationem voluptate necessitatibus dolorum recusandae facere tempora a. Error iure, eaque cupiditate facilis rem atque tenetur modi dolorum aperiam! Dicta nihil qui nam, veritatis officiis consequatur fuga dolores ullam necessitatibus molestiae autem quaerat maxime voluptatum temporibus accusantium expedita nemo facilis rem tenetur recusandae corporis eos ducimus. Ratione id molestias blanditiis ex inventore neque minus iusto, consequuntur omnis error aliquam ab accusantium dignissimos fugit eveniet. Earum, et officiis vero dicta nihil aliquid aperiam. Minima error amet esse possimus necessitatibus vero sequi labore. Nihil deleum perferendis, a excepturi tenetur nobis impedit saepe aspernatur porro. Architecto repudiandae placeat sit laborum voluptatibus veritatis quidem. Suscipit praesentium consequuntur hic reprehenderit soluta delectus libero, excepturi quis ea maxime? Cupiditate animi amet, reiciendis delectus voluptates eaque laudantium accusantium sed recusandae, id corrupti. Quod nulla est veritatis unde laudantium incidunt adipisci cupiditate optio velit repellat illum odit excepturi dolor consequuntur ad, delectus mollitia doloremque, reprehenderit reiciendis recusandae repellendus. Eaque, explicabo labore!
            </div>
        </div>

        <div class="tab-pane fade" id="noticia_3" role="tabpanel" aria-labelledby="noticia_3-tab">
            <br></br>
            <div class="align-text-justify">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos fuga assumenda labore ratione at rerum quibusdam ipsam eveniet cumque doloribus sequi consequuntur dolore animi itaque, atque quaerat quisquam facere autem nobis tenetur vitae quas saepe! Dolorum aspernatur fuga quam explicabo officiis aliquam consequatur deserunt dolores cupiditate eligendi cum nobis doloremque nisi voluptatem illo, maiores itaque eveniet fugiat, veniam exercitationem quo. Sit amet quam beatae quasi harum perspiciatis dolore illum ut consectetur, dolorem quo, explicabo aspernatur odio, velit debitis asperiores voluptas. Laudantium cupiditate eos laboriosam error. Ratione aliquam veniam cum error unde illo repellendus dignissimos corrupti neque eius deleniti omnis inventore praesentium laudantium id, doloremque iusto repudiandae officiis! Similique expedita cumque vel consectetur deserunt magni, perspiciatis aliquid aut beatae distinctio quo at minus corporis doloremque reprehenderit nostrum voluptatum facere voluptate quae fuga. Ipsum commodi enim accusantium dolor, obcaecati dicta? Debitis magnam architecto fugit impedit necessitatibus fugiat at iure quae assumenda quod voluptas similique labore quaerat cum illo repellat, vel dolorem nulla maiores sed consequuntur? Eum praesentium exercitationem ea nisi veritatis aut quasi, architecto quia non neque? Accusamus dolorum, nesciunt perferendis vitae ipsa nam labore reiciendis consectetur nemo voluptatum inventore, doloribus adipisci. Consequuntur quibusdam officia corrupti dolorum fugit molestiae. Quibusdam fugiat ad voluptatem, culpa facilis sed error, ratione illo enim saepe cum voluptatum explicabo eveniet, eligendi asperiores exercitationem voluptate necessitatibus dolorum recusandae facere tempora a. Error iure, eaque cupiditate facilis rem atque tenetur modi dolorum aperiam! Dicta nihil qui nam, veritatis officiis consequatur fuga dolores ullam necessitatibus molestiae autem quaerat maxime voluptatum temporibus accusantium expedita nemo facilis rem tenetur recusandae corporis eos ducimus. Ratione id molestias blanditiis ex inventore neque minus iusto, consequuntur omnis error aliquam ab accusantium dignissimos fugit eveniet. Earum, et officiis vero dicta nihil aliquid aperiam. Minima error amet esse possimus necessitatibus vero sequi labore. Nihil deleum perferendis, a excepturi tenetur nobis impedit saepe aspernatur porro. Architecto repudiandae placeat sit laborum voluptatibus veritatis quidem. Suscipit praesentium consequuntur hic reprehenderit soluta delectus libero, excepturi quis ea maxime? Cupiditate animi amet, reiciendis delectus voluptates eaque laudantium accusantium sed recusandae, id corrupti. Quod nulla est veritatis unde laudantium incidunt adipisci cupiditate optio velit repellat illum odit excepturi dolor consequuntur ad, delectus mollitia doloremque, reprehenderit reiciendis recusandae repellendus. Eaque, explicabo labore!
            </div>
        </div>

        <div class="tab-pane fade" id="noticia_4" role="tabpanel" aria-labelledby="noticia_4-tab">
            <br></br>  
            <div class="align-text-justify">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos fuga assumenda labore ratione at rerum quibusdam ipsam eveniet cumque doloribus sequi consequuntur dolore animi itaque, atque quaerat quisquam facere autem nobis tenetur vitae quas saepe! Dolorum aspernatur fuga quam explicabo officiis aliquam consequatur deserunt dolores cupiditate eligendi cum nobis doloremque nisi voluptatem illo, maiores itaque eveniet fugiat, veniam exercitationem quo. Sit amet quam beatae quasi harum perspiciatis dolore illum ut consectetur, dolorem quo, explicabo aspernatur odio, velit debitis asperiores voluptas. Laudantium cupiditate eos laboriosam error. Ratione aliquam veniam cum error unde illo repellendus dignissimos corrupti neque eius deleniti omnis inventore praesentium laudantium id, doloremque iusto repudiandae officiis! Similique expedita cumque vel consectetur deserunt magni, perspiciatis aliquid aut beatae distinctio quo at minus corporis doloremque reprehenderit nostrum voluptatum facere voluptate quae fuga. Ipsum commodi enim accusantium dolor, obcaecati dicta? Debitis magnam architecto fugit impedit necessitatibus fugiat at iure quae assumenda quod voluptas similique labore quaerat cum illo repellat, vel dolorem nulla maiores sed consequuntur? Eum praesentium exercitationem ea nisi veritatis aut quasi, architecto quia non neque? Accusamus dolorum, nesciunt perferendis vitae ipsa nam labore reiciendis consectetur nemo voluptatum inventore, doloribus adipisci. Consequuntur quibusdam officia corrupti dolorum fugit molestiae. Quibusdam fugiat ad voluptatem, culpa facilis sed error, ratione illo enim saepe cum voluptatum explicabo eveniet, eligendi asperiores exercitationem voluptate necessitatibus dolorum recusandae facere tempora a. Error iure, eaque cupiditate facilis rem atque tenetur modi dolorum aperiam! Dicta nihil qui nam, veritatis officiis consequatur fuga dolores ullam necessitatibus molestiae autem quaerat maxime voluptatum temporibus accusantium expedita nemo facilis rem tenetur recusandae corporis eos ducimus. Ratione id molestias blanditiis ex inventore neque minus iusto, consequuntur omnis error aliquam ab accusantium dignissimos fugit eveniet. Earum, et officiis vero dicta nihil aliquid aperiam. Minima error amet esse possimus necessitatibus vero sequi labore. Nihil deleum perferendis, a excepturi tenetur nobis impedit saepe aspernatur porro. Architecto repudiandae placeat sit laborum voluptatibus veritatis quidem. Suscipit praesentium consequuntur hic reprehenderit soluta delectus libero, excepturi quis ea maxime? Cupiditate animi amet, reiciendis delectus voluptates eaque laudantium accusantium sed recusandae, id corrupti. Quod nulla est veritatis unde laudantium incidunt adipisci cupiditate optio velit repellat illum odit excepturi dolor consequuntur ad, delectus mollitia doloremque, reprehenderit reiciendis recusandae repellendus. Eaque, explicabo labore!
            </div>
        </div>



    </div>
</div>
<?php include('Include/Footer.php') ?>